#SITE CONFIGURATION

title: CarlosManuel Aceves
description: Musician/Musicologist
repository: "carlosmanuelaceeves/music-portfolio"
baseurl: 
url: "http://carlosmanuelaceves.com"

google_tag_manager: GTM-P7PZFVP

# SEO PLUGIN

social:
  name: CarlosManuel Aceves 
  links:
    - https://www.facebook.com/carlosmanuelaceves
    - https://www.instagram.com/carlosmanuelaceves
    - https://www.youtube.com/user/andrewstiefel
    - https://github.com/andrewstiefel
    
#THEME SETTINGS

navigation: # Navigation links
  - {name: 'Music', link: '/music'}
  - {name: 'Recordings', link: '/recordings'}
  - {name: 'Contact', link: '/contact'}
  
email: carlosmanuelaceves@gmail.com
twitter_username: andrewstiefel
github_username: andrewstiefel
instagram_username: carlosmanuelaceves
facebook_username: andrewstiefel
linkedin_username: andrewstiefel

#BUILD SETTINGS

markdown: kramdown
include: ['_pages']
permalink: /blog/:title

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
