#SITE CONFIGURATION

title: Mariachi Tallahasse
description: Tallahassee/s Premier Mariachi
repository: "mariachitallahasse/music-portfolio"
baseurl: 
url: "http://mariachitallahassee.com"

google_tag_manager: GTM-P7PZFVP

# SEO PLUGIN

social:
  name: Mariachi Tallahassee
  links:
    - https://www.facebook.com/mariachitallahassee
    - https://www.instagram.com/mariachitallahassee
    - https://www.youtube.com/user/mariachitallahassee
    
    
#THEME SETTINGS

navigation: # Navigation links
  - {name: 'Music', link: '/music'}
  - {name: 'Recordings', link: '/recordings'}
  - {name: 'Contact', link: '/contact'}
  
email: grupoclassico1@gmail.com
instagram_username: mariachitallahassee
facebook_username: mariachitallahassee

#BUILD SETTINGS

markdown: kramdown
include: ['_pages']
permalink: /blog/:title

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

compress_html:
  clippings: all

plugins: 
  - jekyll-sitemap
  - jekyll-seo-tag
